
# client_dll
dwEntityList: 24910160
dwForceAttack: 23862896
dwForceAttack2: 23863040
dwForceBackward: 23863616
dwForceCrouch: 23864336
dwForceForward: 23863472
dwForceJump: 23864192
dwForceLeft: 23863760
dwForceRight: 23863904
dwGameEntitySystem: 26137168
dwGameEntitySystem_getHighestEntityIndex: 5392
dwGameRules: 25288776
dwGlobalVars: 23846040
dwGlowManager: 25286576
dwInterfaceLinkList: 26324712
dwLocalPlayerController: 25235272
dwLocalPlayer: 14596508
m_iObserverMode: 13192
m_hObserverTarget: 13212
m_iHealth: 256
m_iFOVStart: 12788
m_bIsScoped: 39284
m_vecOrigin: 312
m_vecViewOffset: 264
m_vecVelocity: 276
dwClientState: 5894556
dwClientState_ViewAngles: 19856
m_hActiveWeapon: 12040
m_iItemDefinitionIndex: 12218
m_iClip1: 12916
dwLocalPlayerPawn: 23891768
dwPlantedC4: 25315976
dwPrediction: 23891456
dwSensitivity: 25292104
dwSensitivity_sensitivity: 64
dwViewAngles: 25693632
dwViewMatrix: 25297232
dwViewRender: 25299352
# engine2_dll
dwBuildNumber: 5112788
dwNetworkGameClient: 5110152
dwNetworkGameClient_getLocalPlayer: 240
dwNetworkGameClient_maxClients: 592
dwNetworkGameClient_signOnState: 576
dwWindowHeight: 5860892
dwWindowWidth: 5860888
# inputsystem_dll
dwInputSystem: 218976
