##signatures

anim_overlays = 10640
clientstate_choked_commands = 19760
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19756
clientstate_net_channel = 156
convar_name_hash_table = 197024
dwClientState = 5894556
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19784
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21184
dwClientState_State = 264
dwClientState_ViewAngles = 19856
dwEntityList = 24910160
dwForceAttack = 23862896
dwForceAttack2 = 23863040
dwForceBackward = 23863616
dwForceForward = 23863472
dwForceJump = 23864192
dwForceLeft = 23863760
dwForceRight = 23863904
dwGameEntitySystem = 26137168
dwGameEntitySystem_getHighestEntityIndex = 5392
dwGameDir = 6532608
dwGameRules = 25288776
dwGetAllClasses = 14733220
dwGlobalVars = 23846040
dwGlowManager = 25286576
dwInput = 86369792
dwInterfaceLinkList = 26324712
dwLocalPlayerController = 25235272
dwPlantedC4 = 25315976
dwPrediction = 23891456
dwLocalPlayerPawn = 23891800
dwMouseEnable = 86221408
dwMouseEnablePtr = 86221360
dwPlayerResource = 52613584
dwRadarBase = 86211332
dwSensitivity = 25292104
dwSensitivity_sensitivity = 64
dwSetClanTag = 580272
dwViewMatrix = 25297232
dwViewAngles = 25693632
dwViewRender = 25299352
dwWeaponTable = 86374108
dwWeaponTableIndex = 12908
dwYawPtr = 14612808
dwZoomSensitivityRatioPtr = 14635960
dwbSendPackets = 905938
dwppDirect3DDevice9 = 680640
find_hud_element = 1495672512
force_update_spectator_glow = 4045066
interface_engine_cvar = 260764
is_c4_owner = 4100384
m_bDormant = 237
m_bIsLocalPlayer = 13864
m_flSpawnTime = 66496
m_pStudioHdr = 10576
m_pitchClassPtr = 86221144
m_yawClassPtr = 14612808
model_ambient_min = 5902740
set_abs_angles = 2002880
set_abs_origin = 2002432

#engine2_dll
dwBuildNumber = 5112788
dwNetworkGameClient = 5110152
dwNetworkGameClient_getLocalPlayer = 240
dwNetworkGameClient_maxClients = 592
dwNetworkGameClient_signOnState = 576
dwWindowHeight = 5860892
dwWindowWidth = 5860888

#GameInfo
buildNumber = 13983

#inputsystem_dll
dwInputSystem = 218976

##netvars

cs_gamerules_data = 0
m_ArmorValue = 5392
m_Collision = 2792
m_CollisionGroup = 94
m_localLifeState = 12236
m_MoveType = 1053
m_OriginalOwnerXuidHigh = 5548
m_OriginalOwnerXuidLow = 5544
m_SurvivalGameRuleDecisionTypes = 4904
m_SurvivalRules = 3328
m_aimPunchAngle = 5916
m_aimPunchAngleVel = 5928
m_angEyeAngles = 5400
m_bBombDefused = 3796
m_bBombPlanted = 6763
m_bBombTicking = 3712
m_bFreezePeriod = 48
m_bGunGameImmunity = 5060
m_bHasDefuser = 64
m_bHasHelmet = 65
m_bInReload = 5860
m_bIsDefusing = 5040
m_bIsQueuedMatchmaking = 144
m_bIsScoped = 5032
m_bIsValveDS = 152
m_bSpotted = 8
m_bSpottedByMask = 12
m_bStartedArming = 6712
m_clrRender = 2675
m_fAccuracyPenalty = 5824
m_fFlags = 99
m_flC4Blow = 3760
m_flDefuseCountDown = 3792
m_flDefuseLength = 3788
m_flFallbackWear = 5368
m_flFlashDuration = 5232
m_flFlashMaxAlpha = 5228

m_flLowerBodyYawTarget = 5112
m_flNextAttack = 192
m_flNextPrimaryAttackTickRatio = 5476
m_flSimulationTime = 908
m_flTimerLength = 3768
m_hActiveWeapon = 96
m_hBombDefuser = 3800
m_hMyWeapons = 72
m_hPawn = 1548
m_hController = 4668
m_hPawn = 1548
m_hObserverTarget = 68
m_hOwner = 10716
m_hOwnerEntity = 1048
m_hViewModel = 64
m_iAccountID = 472
m_iClip1 = 5488
m_iClip2 = 5492
m_iCompetitiveRanking = 1904
m_iCompetitiveWins = 1908
m_iCrosshairTextureId = 5736
m_iEntityQuality = 444
m_iFOV = 528
m_iFOVStart = 532
m_iHealth = 812
m_iItemDefinitionIndex = 442
m_iItemIDHigh = 464
m_iObserverMode = 64
m_iObserverLastMode = 72
m_pObserverServices = 4288
m_iShotsFired = 5152
m_iState = 5716
m_iTeamNum = 959
m_lifeState = 816
m_nBombSite = 3716
m_nFallbackPaintKit = 5360
m_nFallbackSeed = 5364
m_nFallbackStatTrak = 5372
m_nForceBone = 3316
m_nModelID = 8
m_nTickBase = 1544
m_nViewModelIndex = 3732
m_szCustomName = 720
m_szLastPlaceName = 5876
m_thirdPersonHeading = 4952
m_vecOrigin = 1344
m_vecVelocity = 984
m_vecViewOffset = 3144
m_zoomLevel = 6672
