dwViewMatrix = 25297232
dwLocalPlayerPawn = 23891768
dwEntityList = 24910160
m_hPlayerPawn = 2028
m_iHealth = 812
m_lifeState = 816
m_iTeamNum = 959
m_vOldOrigin = 4644
m_pGameSceneNode = 784
m_modelState = 352
m_boneArray = 128
m_nodeToWorld = 16
m_sSanitizedPlayerName = 1872
build_number = 13983
dwEntityList = 24910160
dwLocalPlayerController = 25235272
dwLocalPlayer = 25235272
dwViewMatrix =  25297232
dwBuildNumber = 5112788
dwPlantedC4 = 25315976
m_flC4Blow = 3760
m_flNextBeep = 3756
m_flTimerLength = 3768
m_pInGameMoneyServices = 1792
m_iAccount = 64
m_vecAbsOrigin = 200
m_pGameSceneNode = 784
m_flFlashOverlayAlpha = 5220
m_bIsDefusing = 5040
m_szName = 3096
m_pClippingWeapon = 4784
m_ArmorValue = 5392
m_iHealth = 812
m_hPlayerPawn = 2028
m_sSanitizedPlayerName = 1872
m_iTeamNum = 959
m_vecOrigin = 4644
dwEntityList = 24910160
dwLocalPlayer = 25235272
dwViewAngles = 25693632

dwViewMatrix = 25297232
dwPawnHealth = 2040
dwPlayerPawn = 2028
dwSanitizedName = 1872
m_bIsLocalPlayerController = 1744
m_iHealth = 812
m_iTeamNum = 959
m_vOldOrigin = 4644

m_iObserverMode = 13192
m_hObserverTarget = 13212
m_iFOVStart = 12792
m_vecVelocity = 276
dwClientState = 5894556
m_hActiveWeapon = 12040
m_iItemDefinitionIndex = 12218
m_iClip1 = 12916
m_bIsScoped = 39284
m_vecViewOffset = 264
